name: ClearInv
main: com.wwsean08.clear.Clear
version: 2.0.1
website: www.wwsean08.com
author: wwsean08
description: this is a plugin for players to selectively clear their inventory
softdepend: [LWC]

commands:
   clear:
      description: This will clear or selectively clear your inventory
      usage: /<command> [item]...
   preview:
      description: This will give you a preview  of another users inventory.
      usage: /<command> <user>
   unpreview:
       description: This will restore your inventory to it's original state
       usage: /<command>
       aliases: [revert]
permissions:
    clear.self:
        description: Allows you to clear stuff from your own inventory.
        default: true
    clear.other:
        description: Allows you to clear other players inventory and preview their inventory as well.
        default: op
    clear.admin:
        descriptions: Allows you to clear everyones inventory at once.
        default: op
    preview.normal:
        description: Allows you to have a normal preview of a player (non-continuous).
        default: op
    preview.continuous:
        description: Allows you to have a continuous preview of a players inventory.
        default: op